#!/bin/bash

set -e

# Get name of ENDF file
if [[ $# -lt 1 ]]; then
    echo "Need to specify ENDF filename"
    exit 1
fi

# Create new directory for run
if [[ $# -ge 2 ]]; then
    directory=$2
else
    directory=$(date +"%Y-%m-%d-%H%M%S")
fi
mkdir -p $directory

# 1) Copy modified file
cp $1 ${directory}/modified.endf

# 2) Run NJOY
./run-njoy modified.endf ${directory} | tee ${directory}/run-njoy.out

# 3) Modify cross sections for OpenMC use
./modify-csxml ${directory}

# 4) Run benchmarks
./run-benchmarks ${directory}
