#!/bin/bash

# Copy ENDF file to name NJOY will recognize
cp junk.endf tape20

# Run NJOY
njoy < njoy-input

# NJOY produces the following files:
#   tape22 = PENDF with resonances reconstructed
#   tape23 = Broadened PENDF file
#   tape24 = " + heating numbers
#   tape25 = " + gas production
#   tape61 = Thermal scattering data
#   tape26 = Probability tables
#   tape27 = ACE file
#   tape28 = xsdir file

# Removed unneeded outputs
for i in 20 22 23 24 25 61 26; do
    rm -f tape$i
done

# Rename ACE file and xsdir
mv tape27 ace
mv tape28 xsdir
