#!/bin/bash

if [[ $# -lt 1 ]]; then
    echo Must supply name of ENDF file
    exit
fi

# Change directory if supplied
if [[ $# -ge 2 ]]; then
    cd $2
fi

# Copy ENDF file to name NJOY will recognize
cp $1 tape20

# Run NJOY
njoy <<EOF
reconr / Reconstruct XS for neutrons
20 22
'ENDF/B-VII.1 PENDF for 94-Pu-239'/
9437 2/
0.001 0.0 0.003/ err tempr errmax
'ENDF/B-VII.1: 94-Pu-239'/
'Processed by NJOY99.396'/
0/
broadr / Doppler broaden XS
20 22 23
9437 1 0 0 0./
0.001 -2.0e+6 0.003/ errthn thnmax errmax
300.
0/
heatr / Add heating kerma and damage energy
20 23 24/
9437 7 0 0 0 2/
302 303 304 318 402 443 444/
gaspr / Add gas production
20 24 25
thermr / Add thermal scattering data
  0 25 61
0 9437 12 1 1 0 1 221 1/
300.
0.001 4.0
purr / Process Unresolved Resonance Range if any
20 61 26
9437 1 5 20 64/ matd ntemp nsigz nbin nladr
300.
1.E+10 1.E+04 1.E+03 1.E+02 1.E+01
0/
acer / Prepare ACE files
20 26 0 27 28
1 0 1 .71 /
'94-Pu-239 from ENDF/B-VII.1, NJOY99.396'/
9437 300.
1 1/
/
stop
EOF

# NJOY produces the following files:
#   tape22 = PENDF with resonances reconstructed
#   tape23 = Broadened PENDF file
#   tape24 = " + heating numbers
#   tape25 = " + gas production
#   tape61 = Thermal scattering data
#   tape26 = Probability tables
#   tape27 = ACE file
#   tape28 = xsdir file

# Removed unneeded outputs
for i in 20 22 23 24 25 61 26; do
    rm -f tape$i
done

# Rename ACE file, xsdir, and NJOY output
mv tape27 ace
mv tape28 xsdir
mv output njoy.out

# Convert ACE file to binary
/home/romano/openmc/src/utils/convert_binary.py ace ace
